const images = {
  chbox_selected: require('../Images/chbox_selected_signin_six.png'),
  drawerBG: require('../Images/drawerBG.png'),

  BreadAndPastries: require('../Images/BreadAndPastries.png'),
  Dairy: require('../Images/Dairy.png'),
  Fish: require('../Images/Fish.png'),
  Fruit: require('../Images/Fruit.png'),
  Meat: require('../Images/Meat.png'),
  Vagitable: require('../Images/Vagitable.png'),

  backBlackArrow: require('../Images/backBlackArrow.png'),
  FbIcon: require('../Images/fbicon.png'),
  TWIcon: require('../Images/ic_logo_twitter_signin_ten.png'),

  backArrow: require('../Images/backArrow.png'),
  backBlackArrow: require('../Images/backBlackArrow.png'),
  close_signin_15: require('../Images/close_signin_15.png'),
  back_signin_14: require('../Images/backArrow.png'),


  chbox_selected_signin_seven: require('../Images/chbox_selected_signin_seven.png'),

  backArrowSignUpTen: require('../Images/backArrowGrey.png'),
  backArrowSignUpNine: require('../Images/ic_Left_arrow_black_su09.png'),

  cart: require('../Images/cart.png'),
  search: require('../Images/search.png'),
  facebook: require('../Images/facebook.png'),
  mail: require('../Images/mail.png'),
  wtfourteenbg: require('../Images/wtfourteenbg.png'),
  rightArrowGreen: require('../Images/right_arrow_green.png'),
  menuIcon: require('../Images/ic_menu_white.png'),

  music: require('../Images/music.png'),
  film: require('../Images/film.png'),
  book: require('../Images/book.png'),
  game: require('../Images/game.png'),
  food: require('../Images/food.png'),
  sport: require('../Images/sport.png'),
  fashion: require('../Images/fashion.png'),
  draw: require('../Images/draw.png'),
  travel: require('../Images/travel.png'),
  eclipse: require('../Images/eclipse.png'),

  bgtwentyseven: require('../Images/bgtwentyseven.png'),
  dots: require('../Images/activess.png'),
  ic_check_box: require('../Images/ic_check_box.png'),
  ic_uncheck: require('../Images/ic_uncheck.png'),
  timer: require('../Images/timer.png'),
  likes: require('../Images/likes.png'),
  comments: require('../Images/comments.png'),
  location: require('../Images/location.png'),
  roundedcross: require('../Images/roundedcross.png'),

  //halak
  menuAlert: require('../Images/ic_menu_alert.png'),
  cameraIcon: require('../Images/ic_camera.png'),
  userGroup: require('../Images/ic_user.png'),
  searchGreyIcon: require('../Images/ic_search_grey.png'),
  voiceRecordingIcon: require('../Images/voice.png'),
  heartWhiteIcon: require('../Images/ic_heart_white.png'),
  mapPinIcon: require('../Images/ic_map_pin.png'),
  commentWhiteIcon: require('../Images/ic_comment_white.png'),
  moreWhiteIcon: require('../Images/ic_more_white.png'),
  cloude: require('../Images/cloude.png'),
  nearByIcon: require('../Images/ic_nearby_inactive.png'),
  messageIcon: require('../Images/ic_message.png'),
  discoveryIcon: require('../Images/ic_discovery.png'),
  favouriteIcon: require('../Images/ic_favourite.png'),
  profileIcon: require('../Images/ic_profile.png'),
  nearByActiveIcon: require('../Images/ic_nearby.png'),
  messageActiveIcon: require('../Images/ic_message_active.png'),
  discoveryActiveIcon: require('../Images/ic_discovery_active.png'),
  favouriteActiveIcon: require('../Images/ic_favourite_active.png'),
  profileActiveIcon: require('../Images/ic_profile_active.png'),
  watchIcon: require('../Images/watch.png'),
  mapPinWhite: require('../Images/ic_map_pin.png'),
  heartWhiteEmpty: require('../Images/white_empty_heart.png'),

  gradientTitleBarBG: require('../Images/gradient_bg.png'),
  albumIcon: require('../Images/ic_album.png'),
  createMessage: require('../Images/createMessage.png'),
  chatIcon: require('../Images/chatIcon.png'),
  videoIcon: require('../Images/videoIcon.png'),
  leftChatIndicator: require('../Images/leftChatIndicator.png'),
  rightChatIndicator: require('../Images/rightChatIndicator.png'),
  emoji: require('../Images/emoji.png'),

  cart_icon: require('../Images/cart_icon.png'),
  activeHome: require('../Images/activeHome.png'),
  activeCategory: require('../Images/activeCategory.png'),
  activeGift: require('../Images/activeGift.png'),
  normalHome: require('../Images/normalHome.png'),
  normalCategory: require('../Images/normalCategory.png'),
  normalGift: require('../Images/normalGift.png'),
  heavymetal:require('../Images/heavymetal.png'),
  country:require('../Images/country.png'),
  cartIconWhite: require('../Images/ic_cart.png'),
  sliderIcon: require('../Images/sliderIcon.png'),
  musicIcon: require('../Images/ic_music.png'),
  libraryIcon: require('../Images/ic_library.png'),
  radioIcon: require('../Images/ic_radio.png'),
  myLikesIcon: require('../Images/ic_my_likes.png'),
  search_fab: require('../Images/search_fab.png'),
  artical_fab: require('../Images/artical_fab.png'),
  message_fab: require('../Images/message_fab.png'),
  bell_fab: require('../Images/bell_fab.png'),
  favorite_fab: require('../Images/favorite_fab.png'),
  friends_fab: require('../Images/friends_fab.png'),
  logoutIcon: require('../Images/ic_logout.png'),

  addUserIcon: require('../Images/addUserIcon.png'),
  whiteTriangleIcon: require('../Images/whiteTriangleIcon.png'),
  messageBlueIcon: require('../Images/messageBlueIcon.png'),
  slideUpArrowIcon: require('../Images/ic_slide_up_arrow.png'),

  starFilled1: require('../Images/starFilled1.png'),
  starEmpty1: require('../Images/starEmpty1.png'),
  starHalf1: require('../Images/starHalf1.png'),

  //for Demo
  searchbg: require('../Images/searchbg.png'),

  //Premangi
  blueCameraIcon: require('../Images/blueCameraIcon.png'),
  setting: require('../Images/ic_setting.png'),
  phone: require('../Images/ic_phone.png'),
  video: require('../Images/ic_video.png'),
  google: require('../Images/ic_google.png'),
  addUserGray: require('../Images/ic_add_user_gray.png'),
  settingBlack: require('../Images/ic_setting_black.png'),
  googleWhite: require('../Images/ic_google_white.png'),

  //Viral
  livingRoom: require('../Images/ic_living_room.png'),
  diningRoom: require('../Images/ic_dining_room.png'),
  bookCase: require('../Images/ic_bookcase.png'),
  bedRoom: require('../Images/ic_bedroom.png'),
  tvStand: require('../Images/ic_tv_stand.png'),
  bathRoom: require('../Images/ic_bathroom.png'),


  livingRoomBlue: require('../Images/livingroom_blue.png'),
  diningRoomBlue: require('../Images/diningroom_blue.png'),
  bookCaseBlue: require('../Images/bookcase_blue.png'),
  bedRoomBlue: require('../Images/bedroom_blue.png'),
  tvStandBlue: require('../Images/tv_stands_blue.png'),
  bathRoomBlue: require('../Images/bathroom_blue.png'),

  bellnoti: require('../Images/bellnoti.png'),

  bgtwentyseven: require('../Images/bgtwentyseven.png'),

  mnavigation:require('../Images/mnavigation.png'),
  msignup:require('../Images/msignup.png'),
  msignin:require('../Images/msignin.png'),
  msocial:require('../Images/msocial.png'),
  muser:require('../Images/muser.png'),
  mwalkthrough:require('../Images/mwalkthrough.png'),

    admob: require('../Images/ic_ad_mob.png'),
}

export default images
